# Generated by Django 5.2.4 on 2025-07-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trangvang_crawler', '0002_alter_crawltask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='update_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thông tin cập nhật'),
        ),
    ]
